export const projects = [
	{
		slug: 'yunaplena-presentation',
		title: 'yunaplena presentation',
		category: 'video',
		date: '01/02/2026',
		thumbnail: '/media/portfolio/frame.jpg',
		video: 'https://player.vimeo.com/video/1164695818?badge=0&byline=0&portrait=0&title=0&autopause=0&player_id=0&app_id=58479',
		paragraphs: [
			'Yunaplena is defined as a curated frequency that, much like the phases of the moon, is in constant transformation while always preserving its radiance and essence. It is a proposal that lives within duality, between the sophisticated and the clandestine, the ethereal and the corporeal.',
			'To create a human resonance grounded in real presence and inner coherence, free from masks or labels. Its purpose is to generate an energetic connection and a unique vibration through silent elegance, spiritual sensitivity, and shared enjoyment, inviting those who attune to its frequency to experience art and life authentically and without judgment.',
		],
		credits: ['Art Direction: Yu Vilaseca', 'Filmaker: Piers Garrett'],
		media: [],
	},
	{
		slug: 'limite-0',
		title: 'Límite 0',
		category: 'Fragance',
		date: '14/07/2025',
		thumbnail: '/media/portfolio/DSCF0117.JPG',
		paragraphs: [
			'Limit 0 is a fragrance inspired by the search for the tenth marble.',
			'It tells the story of Elias, who suffers from arithmomania (an obsessive-compulsive disorder). Once he buried ten marbles in the desert, but when he dug them up, one was missing. He decided to bury them again to find the tenth marble, and thus Elias enters an absurd loop of burying and digging up.',
			'The idea of a “limit” is drawn from Gödel’s incompleteness theorem, which states that within any logical system, there are propositions that can neither be proved nor disproved. The protagonist is thus confronted with the boundaries of knowledge, where mathematical logic ceases to provide answers. The number 0 represents origin and emptiness, both the starting point and the point of collapse.',
			'The packaging consists of three distinct elements:',
		],
		list: [
			'The bottle containing the fragrance.',
			'Two metallic ellipses that fit seamlessly together, forming a sculptural object designed to hold and diffuse the scent in the environment.',
			'A transparent sphere made of porous glass that absorbs and projects the perfume.',
		],
		credits: ['Art Direction: Victor Hernández, Marta Anglada, Loy Mejía & Yu Vilaseca'],
		media: [
			'/media/portfolio/DSCF0117.JPG',
			'/media/limite-0/1.jpg',
			'/media/limite-0/DSCF0082.jpg',
			'/media/limite-0/DSCF0063.jpg',
			'/media/limite-0/DSCF0047.jpg',
		],
	},
	{
		slug: 'kracht',
		title: 'Kracht',
		category: 'Food Design',
		date: '07/06/25',
		thumbnail: '/media/portfolio/PHOTO-2025-06-11-08-03-39.jpg',
		paragraphs: [
			'Kracht is a chocolate bonbon inspired by Berlin’s techno scene, particularly Club Tresor and its Detroit roots. To release its citrus notes, the bonbon must be broken before eating-symbolizing the fall of the Berlin Wall. Made with 100% pure chocolate, it was presented alongside live DJ performance of 1990s Berlin techno, echoing the sound of Detroit.',
			'Inspired by the way this political process unfolded alongside a cultural renaissance, especially in the heart of Berlin, amidst both physical and identity reconstruction, became the epicentre of a new underground movement. Out of this context emerged Tresor, the first techno club of a unified Berlin. More than just a gathering place, it embodied a new form of creative, collective, and sensory freedom.',
			'Our concept is built around the idea of an “explosion of freedom”, expressed through flavours, textures, and visual references that evoke both the shadows of the past and the vibrant energy of a new era. Drawing inspiration from the sensory world of techno, its force, repetition, layering, and contrasts, we created a bonbon that represents not only a time and place, but also a profound emotional transformation: that of a society finally able to dance again.',
			'German techno, shaped by the industrial and experimental roots of Detroit Techno, became an artistic expression of cultural openness after decades of division.',
		],
		credits: ['Art Direction: Diego Enrique, Fernando Mareo & Yu Vilaseca'],
		media: [
			'/media/portfolio/PHOTO-2025-06-11-08-03-39.jpg',
			'/media/kracht/kracht2.jpg',
			'/media/kracht/kracht3.jpg',
			'/media/kracht/kracht5.jpg',
		],
	},
	{
		slug: 'tras-la-sombra',
		title: 'Tras La Sombra',
		category: 'Photonovel',
		date: '11/04/2025',
		thumbnail: '/media/portfolio/Mockup_1.jpg',
		paragraphs: [
			'Produced a photonovel of the story of Little Red Riding Hood, using photographer Man Ray and artist Kara Walker as direct references.',
		],
		credits: ['Art Direction: Franca Bassino & Yu Vilaseca', 'Photographer: Albert Martos'],
		media: [
			'/media/portfolio/Mockup_1.jpg',
			'/media/tras-la-sombra/Mockup_2.jpg',
			'/media/tras-la-sombra/Mockup_3.jpg',
			'/media/tras-la-sombra/Mockup_4.jpg',
			'/media/tras-la-sombra/Mockup_5.jpg',
			'/media/tras-la-sombra/Mockup_6.jpg',
			'/media/tras-la-sombra/Mockup_7.jpg',
			'/media/tras-la-sombra/Mockup_8.jpg',
			'/media/tras-la-sombra/Mockup_9.jpg',
		],
	},
	{
		slug: 'synthetic-jomo',
		title: 'Synthetic Jomo',
		category: 'Album Cover',
		date: '27/03/2025',
		thumbnail: '/media/portfolio/cover-05.png',
		paragraphs: [
			'Design of three album covers for the New Wave music genre, created for the fictional artist Shrimp Jesus.',
			'Developed using the COCOTRANS method: Copy, Combine, and Transform.',
			'Each cover was entirely handmade, with no use of computers involved.',
			'By copying the cover of Joy Division, it seemed ideal for what the New Wave era represented, especially considering that the band later became “New Order.” In addition, this cover conveys the waves that can be interpreted both in the context of the musical genre and the artist himself, “Shrimp Jesus.”',
			'Combining the album covers of The Buggles and The Clash, two emblematic bands from the New Wave era. One album critiques emerging technologies, deeply rooted in its own time yet still relevant today, while the other is a pure rock-punk record addressing the social issues of the era.',
			'This contrast perfectly reflects the concept behind the cover: the music genre itself is strongly tied to its historical moment (New Wave), while the fictional phenomenon of Shrimp Jesus brings a contemporary theme, exploring current questions around AI and cultural experimentation.',
			'Finally, I combined the album covers of Kraftwerk, The B-52’s, and Depeche Mode, transforming the lobster into a shrimp (referring to Shrimp Jesus). Kraftwerk was included as they are considered the “fathers” of electronic music, profoundly influencing subgenres such as synth-pop and electropop.',
		],
		credits: ['Art Direction: Yu Vilaseca'],
		media: [
			'/media/synthetic-jomo/cover-03.png',
			'/media/synthetic-jomo/cover-04.png',
			'/media/portfolio/cover-05.png',
		],
	},
];

export const events = [
	['Resident at W Barcelona', 'Hotel W Barcelona', 'House, Soulful, Jackin, Nu-Disco', 'Club & Ambient', 'Now'],
	['Noxe Club', 'W Barcelona, Bcn', 'House', 'Club', 'Jun ‘26'],
	['“Le nozze di Figaro”', 'The Social Hub, Bcn', 'House, Jackin, Nu-Disco', 'Private Event', 'May ‘26'],
	['La Siesta Afterwork', 'Salt Restaurant, Bcn', 'House, Jackin, Soulful', 'Ambient', 'May ‘26'],
	['Sant Jordi W Barcelona', 'Salt Restaurant, Bcn', 'House, Jackin, Soulful', 'Private Event', 'Apr ‘26'],
	['Birthday Party', 'El Patrón Restaurant, Bcn', 'Open format', 'Private Event', 'Apr ‘26'],
	['Open Day Elisava', 'Elisava, Bcn', 'Soulful, Jackin', 'Event', 'Apr ‘26'],
	['Club Motel', 'PNC Radio, Bcn', 'Techno', 'Showcase', 'Mar ‘26'],
	['Casa Très', 'The Pharmacy, Bcn', 'House & Tech house', 'Private Event', 'Feb ‘26'],
	['Club Rodeo x Salto Festival (Half Marathon Event)', 'Trafalgar Pizza Club, Bcn', 'House & Tech house', 'Sport Event', 'Feb ‘26'],
	['Macarena Club x Plastic Academia x Ibiza Sonica Radio', 'Macarena Club, Bcn', 'Deep House / Deep Tech', 'Club', 'Dec ‘25'],
	['Climbat La Foixarda', 'Barcelona', 'House & Tech house', 'Private Event', 'Dec ‘25'],
	['Bulder Planet 10th Anniversary Party', 'Mataró', 'House & Tech house', 'Sport Event', 'Nov ‘25'],
	['G + J Birthday Party', 'Casa Bonay, Bcn', 'House, Disco, Classics', 'Private Party', 'Nov ‘25'],
	['Sumak Terra', 'El Palauet Royal, Bcn', 'House & Latin Tech', 'Private Event', 'Nov ‘25'],
	['Futbol Solidari 10th Anniversary Party', 'Mataró', 'Urban', 'Party', 'Nov ‘25'],
	['Club Rodeo', 'Sea You House, Bcn', 'House & Tech house', 'Sport Event', 'Nov ‘25'],
	['SíSí restaurant inauguration', 'The Social Hub, Bcn', 'Deep House / Deep Tech', 'Private', 'Sep ‘25'],
	['Elisava Degree Show', 'Las Tres Chimeneas, Bcn', 'Techno', 'Showcase', 'Jun ‘25'],
	['La Textil Collective Afterparty', 'La Textil, Bcn', 'House & Tech house', 'Afterparty', 'May ‘25'],
	['Casino Barcelona', 'Casino, Bcn', 'Deep House & Soulful', 'Ambient', 'Apr ‘25'],
	['Macarena Club', 'Macarena Club, Bcn', 'Depp House / Deep Tech', 'Club', 'Apr ‘25'],
	['Bulder Planet', 'Mataró', 'House & Tech house', 'Sport Event', 'Mar ‘25'],
	['Pacha Barcelona', 'Pacha Club, Bcn', 'House & Tech house', 'Club', 'Feb ‘25'],
	['Casino Barcelona', 'Casino, Bcn', 'Deep House & Soulful', 'Ambient', 'Jan ‘25'],
	['Christmas Fair', 'El Moll de la Fusta, Bcn', 'Pop', 'Ambient', 'Dec ‘24'],
];
